### ISSUE TITLE
Justify text

### ISSUE THREAD

**Issue by alexjj** [damiencaselli/paperback#9]
I personally think it would look a lot nicer if all the text was justified. With `text-align: justify` on `<p>` or maybe the whole body.

**Comment by dashdashzako** [comment]
Using justified text is a generally a bad idea on the web platform due to the justification algorithm used by the browsers. It may look nice in some cases, but most of the time some parts of the text will be broken.

Unless justification is done using a better algorithm such as the Knuth-Plass', I'll refrain from using justified text as a default in themes I share.
